# This is a basic workflow to help you get started with Actions

name: CI NODE JS WISE HUB BACKEND RUNNER

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking out repo
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Node Js Executable Env
        uses: actions/setup-node@v4
        with: 
          node-version: 20.x

      # Runs a set of commands using the runners shell
      - name: Install Deps
        run: npm i --force

      - name: Build Nx Project
        run: npx nx build apis
      
      - name: Docker Setup
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build And Push
        uses: docker/build-push-action@v5
        with:
          context: dist/apps/backend/apis/
          file: Dockerfile
          push: true
          tags: coderhunter/wisehub:latest

